//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_EZexeat
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSignUp
    {
        public int UserID { get; set; }
        public string StudentName { get; set; }
        public string SchoolName { get; set; }
        public string HouseName { get; set; }
        public string Prog { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> UserName { get; set; }
        public string nameUser { get; set; }
        public byte[] Data { get; set; }
    }
}
